language: elixir

elixir:
  - '1.10'
otp_release:
  - '22.2.6'
addons:
  postgres: '9.4'

services:
  - postgresql

env:
  - MIX_ENV=test

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.travis
